name: 'Create Profile VC'

on: workflow_dispatch

jobs:
  profile: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: actor
        uses: ./
        with:
          url: ${{secrets.AGENT_URL}}
          token: ${{secrets.AGENT_TOKEN}}
          method: didManagerGetOrCreate
          args: '{ "provider": "did:web", "alias": "bob-did.eu.ngrok.io:"${{github.actor}} }'
      
      - run: echo ${{ fromJSON(steps.actor.outputs.result).did }}
      
      # - id: vc
      #   uses: ./
      #   with:
      #     url: ${{secrets.AGENT_URL}}
      #     token: ${{secrets.AGENT_TOKEN}}
      #     method: didManagerGetOrCreate
      #     args: '{ "provider": "did:web", "alias": "bob-did.eu.ngrok.io" }'
      