name: 'Create Profile VC'

on: workflow_dispatch

jobs:
  profile: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Creating actor DID
      - id: actor
        uses: ./
        with:
          url: ${{secrets.AGENT_URL}}
          token: ${{secrets.AGENT_TOKEN}}
          method: didManagerGetOrCreate
          args: |
            { 
              "provider": "did:ethr:rinkeby",
              "alias": "${{github.actor}}@github" 
            }
      
      - run: echo ${{ fromJSON(steps.actor.outputs.result).did }}

      # Creating self signed Profile Verifiable Credential
      - id: vc
        uses: ./
        with:
          url: ${{secrets.AGENT_URL}}
          token: ${{secrets.AGENT_TOKEN}}
          method: createVerifiableCredential
          args: |
            {
              "save": true,
              "proofFormat": "jwt",
              "credential": {
                "type": [
                  "VerifiableCredential",
                  "Profile"
                ],
                "issuer": { 
                  "id": "${{ fromJSON(steps.actor.outputs.result).did }}" 
                },
                "credentialSubject": {
                  "id": "${{ fromJSON(steps.actor.outputs.result).did }}",
                  "nickname": "${{github.actor}}",
                  "url": "https://github.com/${{github.actor}}",
                }
              }
            }
      
      - run: echo ${{ fromJSON(steps.vc.outputs.result).proof.jwt }}