name: 'Create Profile VC'

on: workflow_dispatch

jobs:
  profile: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Creating actor DID
      - id: actor
        uses: ./
        with:
          url: ${{secrets.AGENT_URL}}
          token: ${{secrets.AGENT_TOKEN}}
          method: didManagerGetOrCreate
          args: |
            { 
              "provider": "did:ethr:rinkeby",
              "alias": "${{github.actor}}@github" 
            }
      
      - run: echo ${{ fromJSON(steps.actor.outputs.result).did }}

      - uses: octokit/graphql-action@v2.x
        id: viewer
        with:
          query: |
            query { 
              viewer { 
                login
                avatarUrl
                name
                url
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'Actor name: ${{ fromJSON(steps.viewer.outputs.data).viewer.name }}'"

      # Creating self signed Profile Verifiable Credential
      - id: vc
        uses: ./
        with:
          url: ${{secrets.AGENT_URL}}
          token: ${{secrets.AGENT_TOKEN}}
          method: createVerifiableCredential
          args: |
            {
              "save": true,
              "proofFormat": "jwt",
              "credential": {
                "type": [
                  "VerifiableCredential",
                  "Profile"
                ],
                "issuer": { 
                  "id": "${{ fromJSON(steps.actor.outputs.result).did }}" 
                },
                "credentialSubject": {
                  "id": "${{ fromJSON(steps.actor.outputs.result).did }}",
                  "name": "${{ fromJSON(steps.viewer.outputs.data).viewer.name }}",
                  "nickname": "${{github.actor}}",
                  "picture": "${{ fromJSON(steps.viewer.outputs.data).viewer.avatarUrl }}",
                  "url": "${{ fromJSON(steps.viewer.outputs.data).viewer.url }}"
                }
              }
            }
      
      - run: echo ${{ fromJSON(steps.vc.outputs.result).proof.jwt }}