name: 'resolve did'

on: workflow_dispatch

jobs:
  record: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          url: ${{secrets.AGENT_URL}}
          token: ${{secrets.AGENT_TOKEN}}
          method: ${{ 'resolveDid' }}
          args: ${{ '{"didUrl": "did:web:sun.veramo.io"}' }}
